output-dir: "{cwd}/generated"
emit:
  - "@typespec/openapi3"
  - "@typespec/http-client-js"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/oas"
    openapi-versions:
      - 3.1.0
  "@typespec/http-client-js":
    emitter-output-dir: "{output-dir}/clients/js"
