name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: CI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Setup mise
        uses: jdx/mise-action@v3

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v5
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('**/bun.lock') }}

      - name: Install packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: mise run install

      - name: Check format
        run: mise run format:check

      - name: Check generate code has diff
        run: |
          mise run compile:all
          if [ -n "$(git status --porcelain | grep generated)" ]; then
            echo "自動生成コードに差分があります"
            git status
            exit 1
          fi
